// All 83 cards. Each card has a stable numeric id.
// Units: { id, name, cls, rarity, type:"unit", cost, ap, keyword, n, e, s, w, ability }
// Commands: { id, name, rarity, type:"command", cost, ap, effect }
// Missions: { id, name, rarity, type:"mission", cost, ap, req, reward, limitTurns }
// Objectives: { id, name, type:"objective", category, l1, l2, l3, l4 }

export const CARDS = [
  // ── UNITS ──────────────────────────────────────────────────────────────
  { id:1,  name:"Rifle Squad",         cls:"Infantry",  rarity:"Common", type:"unit", cost:1, ap:1,  keyword:null,           n:4, e:3, s:4, w:3, ability:null },
  { id:2,  name:"Riflemen",            cls:"Infantry",  rarity:"Common", type:"unit", cost:1, ap:1,  keyword:"Guard",         n:4, e:3, s:2, w:3, ability:null },
  { id:3,  name:"Fallschirmjäger",     cls:"Infantry",  rarity:"Common", type:"unit", cost:2, ap:2,  keyword:"Airborne",      n:5, e:5, s:2, w:2, ability:null },
  { id:4,  name:"Mortar Team",         cls:"Infantry",  rarity:"Common", type:"unit", cost:2, ap:2,  keyword:"Bombard",       n:5, e:2, s:4, w:2, ability:null },
  { id:5,  name:"Supply Runner",       cls:"Infantry",  rarity:"Common", type:"unit", cost:1, ap:2,  keyword:null,           n:3, e:3, s:3, w:3, ability:"Control objective at turn end → gain 1 Fuel." },
  { id:6,  name:"Halftrack",           cls:"Tank",      rarity:"Common", type:"unit", cost:2, ap:2,  keyword:"Armor",         n:5, e:4, s:1, w:4, ability:null },
  { id:7,  name:"Blitz Tank",          cls:"Tank",      rarity:"Common", type:"unit", cost:3, ap:4,  keyword:"Breakthrough",  n:5, e:5, s:5, w:5, ability:null },
  { id:8,  name:"Tank Hunter",         cls:"Tank",      rarity:"Common", type:"unit", cost:3, ap:3,  keyword:"Double Attack", n:6, e:6, s:3, w:2, ability:null },
  { id:9,  name:"Heavy Tank",          cls:"Tank",      rarity:"Common", type:"unit", cost:4, ap:4,  keyword:"Heavy Armor",   n:5, e:4, s:4, w:4, ability:null },
  { id:10, name:"Field Howitzer",      cls:"Artillery", rarity:"Common", type:"unit", cost:2, ap:1,  keyword:"Bombard",       n:4, e:3, s:4, w:3, ability:null },
  { id:11, name:"Anti-Tank Gun",       cls:"Artillery", rarity:"Common", type:"unit", cost:2, ap:2,  keyword:"Guard",         n:2, e:6, s:2, w:6, ability:null },
  { id:12, name:"Fighter",             cls:"Aircraft",  rarity:"Common", type:"unit", cost:3, ap:3,  keyword:"Airborne",      n:7, e:6, s:5, w:1, ability:null },
  { id:13, name:"Dive Bomber",         cls:"Aircraft",  rarity:"Common", type:"unit", cost:3, ap:4,  keyword:"Double Attack", n:7, e:1, s:7, w:2, ability:null },
  { id:14, name:"Field Commander",     cls:"Commander", rarity:"Rare",   type:"unit", cost:4, ap:4,  keyword:"Inspire",       n:6, e:6, s:6, w:6, ability:null },
  { id:15, name:"River Gunboat",       cls:"Naval",     rarity:"Common", type:"unit", cost:2, ap:1,  keyword:"Bombard",       n:2, e:5, s:2, w:5, ability:null },
  { id:34, name:"Scouts",              cls:"Infantry",  rarity:"Common", type:"unit", cost:1, ap:1,  keyword:null,           n:5, e:5, s:1, w:1, ability:null },
  { id:35, name:"Mountain Troops",     cls:"Infantry",  rarity:"Common", type:"unit", cost:2, ap:2,  keyword:null,           n:4, e:5, s:4, w:5, ability:null },
  { id:36, name:"Heavy Machine Gun Team", cls:"Infantry", rarity:"Common", type:"unit", cost:2, ap:2, keyword:"Guard",        n:6, e:2, s:6, w:2, ability:null },
  { id:37, name:"Paratrooper Veterans",cls:"Infantry",  rarity:"Common", type:"unit", cost:3, ap:3,  keyword:"Airborne",      n:5, e:5, s:2, w:6, ability:null },
  { id:38, name:"Panzer II",           cls:"Tank",      rarity:"Common", type:"unit", cost:1, ap:1,  keyword:null,           n:5, e:2, s:5, w:2, ability:null },
  { id:39, name:"Sherman Tank",        cls:"Tank",      rarity:"Common", type:"unit", cost:3, ap:3,  keyword:"Armor",         n:7, e:6, s:4, w:1, ability:null },
  { id:40, name:"Flak Halftrack",      cls:"Tank",      rarity:"Common", type:"unit", cost:2, ap:2,  keyword:"Bombard",       n:6, e:5, s:2, w:1, ability:null },
  { id:41, name:"Tank Destroyer",      cls:"Tank",      rarity:"Common", type:"unit", cost:4, ap:4,  keyword:"Breakthrough",  n:9, e:3, s:9, w:3, ability:null },
  { id:42, name:"Rocket Launcher",     cls:"Artillery", rarity:"Common", type:"unit", cost:3, ap:4,  keyword:"Bombard",       n:5, e:1, s:1, w:1, ability:null },
  { id:43, name:"Anti-Aircraft Gun",   cls:"Artillery", rarity:"Common", type:"unit", cost:2, ap:2,  keyword:"Guard",         n:6, e:5, s:4, w:1, ability:null },
  { id:44, name:"Recon Plane",         cls:"Aircraft",  rarity:"Common", type:"unit", cost:2, ap:3,  keyword:"Airborne",      n:6, e:4, s:4, w:1, ability:null },
  { id:45, name:"Heavy Bomber",        cls:"Aircraft",  rarity:"Common", type:"unit", cost:4, ap:5,  keyword:"Bombard",       n:6, e:6, s:6, w:6, ability:null },
  { id:46, name:"Landing Craft",       cls:"Naval",     rarity:"Common", type:"unit", cost:1, ap:1,  keyword:null,           n:7, e:4, s:2, w:1, ability:null },
  { id:47, name:"Destroyer",           cls:"Naval",     rarity:"Common", type:"unit", cost:3, ap:2,  keyword:"Armor",         n:8, e:1, s:8, w:1, ability:null },
  { id:48, name:"Ace Pilot",           cls:"Aircraft",  rarity:"Common", type:"unit", cost:4, ap:4,  keyword:"Double Attack", n:8, e:8, s:3, w:3, ability:null },
  { id:59, name:"Storm Squad",         cls:"Infantry",  rarity:"Common", type:"unit", cost:2, ap:2,  keyword:"Double Attack", n:4, e:1, s:5, w:3, ability:null },
  { id:60, name:"Vanguard Tank",       cls:"Tank",      rarity:"Common", type:"unit", cost:2, ap:2,  keyword:"Breakthrough",  n:6, e:5, s:4, w:1, ability:null },
  { id:61, name:"Shock Troopers",      cls:"Infantry",  rarity:"Common", type:"unit", cost:1, ap:1,  keyword:"Double Attack", n:3, e:2, s:3, w:2, ability:null },
  { id:62, name:"Bunker Crew",         cls:"Infantry",  rarity:"Common", type:"unit", cost:3, ap:2,  keyword:"Guard",         n:7, e:2, s:7, w:2, ability:null },
  { id:63, name:"Self-Propelled Gun",  cls:"Artillery", rarity:"Common", type:"unit", cost:3, ap:3,  keyword:"Armor",         n:9, e:1, s:1, w:4, ability:null },
  { id:64, name:"Veteran Garrison",    cls:"Infantry",  rarity:"Common", type:"unit", cost:4, ap:4,  keyword:"Guard",         n:7, e:6, s:7, w:4, ability:null },
  { id:65, name:"Panzer Brigade",      cls:"Tank",      rarity:"Common", type:"unit", cost:3, ap:3,  keyword:"Heavy Armor",   n:5, e:4, s:2, w:2, ability:null },
  { id:66, name:"King Tiger",          cls:"Tank",      rarity:"Rare",   type:"unit", cost:5, ap:4,  keyword:"Heavy Armor",   n:4, e:7, s:6, w:6, ability:null },
  { id:67, name:"Battleship",          cls:"Naval",     rarity:"Common", type:"unit", cost:4, ap:3,  keyword:"Heavy Armor",   n:5, e:5, s:5, w:1, ability:null },
  { id:68, name:"Chief of Staff",      cls:"Commander", rarity:"Rare",   type:"unit", cost:3, ap:3,  keyword:"Inspire",       n:1, e:8, s:6, w:1, ability:null },
  { id:69, name:"Quartermaster",       cls:"Infantry",  rarity:"Common", type:"unit", cost:1, ap:1,  keyword:null,           n:1, e:1, s:4, w:4, ability:"Start of your turn: if you control 2+ objectives, draw a card." },
  { id:70, name:"Trench Runners",      cls:"Infantry",  rarity:"Common", type:"unit", cost:1, ap:1,  keyword:null,           n:4, e:1, s:6, w:1, ability:null },
  { id:71, name:"Light Skirmishers",   cls:"Infantry",  rarity:"Common", type:"unit", cost:1, ap:1,  keyword:null,           n:1, e:5, s:2, w:5, ability:null },
  { id:72, name:"Reserve Infantry",    cls:"Infantry",  rarity:"Common", type:"unit", cost:2, ap:2,  keyword:null,           n:1, e:6, s:5, w:6, ability:null },
  { id:86, name:"Grenadiers",          cls:"Infantry",  rarity:"Common", type:"unit", cost:3, ap:3,  keyword:null,           n:6, e:6, s:6, w:6, ability:null },

  // ── COMMANDS ───────────────────────────────────────────────────────────
  { id:16, name:"Artillery Barrage",   rarity:"Common", type:"command", cost:2, ap:1, effect:"Remove Armor from 1 enemy unit and Suppress it." },
  { id:17, name:"Blitzkrieg Order",    rarity:"Common", type:"command", cost:2, ap:2, effect:"Choose 1 friendly Tank. It may attack 1 adjacent enemy immediately, as if just deployed." },
  { id:18, name:"Field Medic",         rarity:"Common", type:"command", cost:1, ap:1, effect:"Remove Suppression from 1 friendly unit." },
  { id:19, name:"Tactical Withdrawal", rarity:"Common", type:"command", cost:1, ap:1, effect:"Return 1 friendly unit to your hand. It loses Suppression. Draw 1 card." },
  { id:20, name:"Air Strike",          rarity:"Common", type:"command", cost:3, ap:3, effect:"Deal 1 hit to a single enemy unit for each friendly Aircraft you control." },
  { id:21, name:"Coordinated Strike",  rarity:"Common", type:"command", cost:2, ap:2, effect:"Choose 2 friendly units. Each may attack 1 adjacent enemy this turn." },
  { id:22, name:"Recon",               rarity:"Common", type:"command", cost:2, ap:1, effect:"Draw 3 cards." },
  { id:49, name:"Smoke Screen",        rarity:"Common", type:"command", cost:1, ap:1, effect:"Choose 1 friendly unit. It gains Guard until your next turn." },
  { id:50, name:"Improvised Position", rarity:"Common", type:"command", cost:1, ap:1, effect:"Choose 1 friendly vanilla unit. It gains Armor until your next turn." },
  { id:51, name:"Rally Cry",           rarity:"Common", type:"command", cost:1, ap:1, effect:"Choose up to 2 friendly units. Each gains +1 to all sides until your next turn." },
  { id:52, name:"Forward Observer",    rarity:"Common", type:"command", cost:1, ap:1, effect:"Draw 3 cards. Put 1 on top of your deck and 1 on the bottom. Keep 1." },
  { id:53, name:"Pincer Maneuver",     rarity:"Common", type:"command", cost:3, ap:1, effect:"Choose 2 friendly units on opposite sides of 1 enemy unit. Both attack it." },
  { id:54, name:"Last Stand",          rarity:"Common", type:"command", cost:2, ap:1, effect:"Remove Suppression from 1 friendly unit. It gains Guard until your next turn." },
  { id:73, name:"Overrun",             rarity:"Common", type:"command", cost:2, ap:2, effect:"This turn, every time you Suppress or Destroy an enemy unit, deal 1 additional HQ damage." },
  { id:74, name:"Dig In",              rarity:"Common", type:"command", cost:1, ap:1, effect:"Choose 1 friendly unit adjacent to an objective you control. It gains Guard and Armor until your next turn." },
  { id:75, name:"Hold Position",       rarity:"Common", type:"command", cost:2, ap:1, effect:"Up to 2 friendly units adjacent to an objective you control gain Armor until your next turn." },
  { id:76, name:"Industrial Surge",    rarity:"Common", type:"command", cost:1, ap:1, effect:"At the start of your next turn, gain 2 Fuel." },
  { id:78, name:"Combined Arms Doctrine", rarity:"Common", type:"command", cost:3, ap:3, effect:"Remove Suppression from all units on the board. For each unit cleared this way, your HQ gains 2 HP." },
  { id:79, name:"Suppressing Fire",    rarity:"Common", type:"command", cost:4, ap:4, effect:"Deal 1 hit to a single enemy unit for each friendly Infantry you control." },
  { id:80, name:"Entrench",            rarity:"Common", type:"command", cost:2, ap:2, effect:"Friendly Infantry you control gain +2 to all sides until your next turn." },

  // ── MISSIONS ───────────────────────────────────────────────────────────
  { id:23, name:"Hold the Line",       rarity:"Common", type:"mission", cost:0, ap:0, req:"Control all objectives at end of your turn.",                                          reward:"Heal 5 HQ HP.",                          limitTurns:5 },
  { id:24, name:"Deep Strike",         rarity:"Common", type:"mission", cost:1, ap:2, req:"Have a friendly unit adjacent to 2+ enemy units simultaneously.",                      reward:"Deal 2 HQ damage.",                      limitTurns:3 },
  { id:25, name:"Blitz Assault",       rarity:"Common", type:"mission", cost:0, ap:0, req:"Destroy 2 enemy units in a single turn.",                                              reward:"Draw 2 cards and gain 1 Fuel.",          limitTurns:4 },
  { id:55, name:"Armored Spearhead",   rarity:"Common", type:"mission", cost:1, ap:2, req:"Play.",                                                                                reward:"Your next Tank costs 2 less Fuel.",      limitTurns:0 },
  { id:56, name:"Total Air Superiority",rarity:"Common", type:"mission", cost:1, ap:2, req:"Destroy an enemy unit with a friendly Aircraft.",                                    reward:"Deal 2 HQ damage.",                      limitTurns:4 },
  { id:57, name:"Fortify the Line",    rarity:"Common", type:"mission", cost:1, ap:1, req:"Control 2+ objectives at end of your turn.",                                           reward:"Remove Suppression from 1 friendly unit and give it Armor.", limitTurns:5 },
  { id:58, name:"Encirclement",        rarity:"Common", type:"mission", cost:1, ap:1, req:"A friendly unit is adjacent to 1 enemy unit on 2+ sides simultaneously.",              reward:"Deal 1 hit to that enemy unit.",         limitTurns:4 },
  { id:81, name:"Total Onslaught",     rarity:"Common", type:"mission", cost:1, ap:2, req:"Destroy 3 enemy units total this match.",                                              reward:"Deal 2 HQ damage.",                      limitTurns:6 },
  { id:84, name:"Overwhelming Force",  rarity:"Common", type:"mission", cost:1, ap:2, req:"Destroy an enemy unit with a friendly Heavy Armor unit.",                              reward:"Deal 2 HQ damage.",                      limitTurns:5 },

  // ── OBJECTIVES ─────────────────────────────────────────────────────────
  { id:26, name:"Factory",             type:"objective", category:"Economy/Vehicle",  l1:"Gain 1 Fuel.",                                         l2:"Gain 1 Fuel. Next Tank costs 1 less.",              l3:"Gain 2 Fuel. Tanks +1 all sides.",                    l4:"Gain 2 Fuel. Tanks +2 all sides. Deal 2 HQ damage." },
  { id:27, name:"Airfield",            type:"objective", category:"Air/Tempo",        l1:"Aircraft attack twice on placement this turn.",         l2:"Deal 1 HQ damage.",                                l3:"Deal 1 HQ damage. Draw 1 card.",                      l4:"Deal 4 HQ damage." },
  { id:28, name:"Supply Depot",        type:"objective", category:"Resource",          l1:"Gain 1 Fuel.",                                         l2:"Gain 2 Fuel.",                                     l3:"Gain 2 Fuel. Draw 1 card.",                           l4:"Gain 3 Fuel. Draw 1 card. Deal 2 HQ damage." },
  { id:29, name:"Bridge",              type:"objective", category:"Positioning",       l1:"Return 1 friendly unit to hand, remove Suppression.",  l2:"Same. Draw 1 card.",                               l3:"Return up to 2 units, remove Suppression.",           l4:"Return up to 2, remove Suppression. Draw 1 card. Deal 2 HQ damage." },
  { id:30, name:"Radar Station",       type:"objective", category:"Information",       l1:"Look at opponent's hand.",                             l2:"Look at hand. Draw 1 card.",                       l3:"Look; opponent discards 1 you choose.",                l4:"Look; opponent discards 1. Draw 1 card. Deal 2 HQ damage." },
  { id:31, name:"City",                type:"objective", category:"Infantry/Defense",  l1:"Adjacent Infantry gain Guard this turn.",               l2:"Adjacent Infantry +1 all sides this turn.",        l3:"Adjacent Infantry gain Guard, +1 all sides.",         l4:"Adjacent Infantry gain Guard, +2 all sides. Deal 2 HQ damage." },
  { id:32, name:"Artillery Position",  type:"objective", category:"Damage",            l1:"Deal 1 HQ damage.",                                    l2:"Deal 1 hit to 1 enemy unit.",                      l3:"Deal 2 HQ damage.",                                   l4:"Deal 3 HQ damage. Deal 1 hit to 1 enemy unit." },
  { id:33, name:"Fortification",       type:"objective", category:"Defense",           l1:"Adjacent units gain Fortified this turn.",              l2:"Adjacent units gain Fortified until next turn.",   l3:"Adjacent units gain Fortified, +1 all sides.",        l4:"Adjacent units gain Fortified, +2 all sides. Deal 2 HQ damage." },
];

export const CARD_BY_ID = Object.fromEntries(CARDS.map(c => [c.id, c]));
